theme: jekyll-theme-minimal
title: my.monash but usable
description: Although my.monash looks fancy, it is unusable due to unfortunate design choices. The links on this page always display in the same order, no matter what device you are using.
