theme: jekyll-theme-minimal
title: my.monash lite
description: Although my.monash looks fancy, it is slow and difficult to navigate. This is a fast and minimal alternative that always displays links in the same order.
google_analytics: UA-99033104-1
